/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_chat_5fonline_5fack_5fmesg_2eproto__INCLUDED
#define PROTOBUF_C_chat_5fonline_5fack_5fmesg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ChatOnlineAckMesg ChatOnlineAckMesg;


/* --- enums --- */


/* --- messages --- */

struct  _ChatOnlineAckMesg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uid;
  uint64_t uid;
  protobuf_c_boolean has_cid;
  uint64_t cid;
  char *app;
  char *version;
  protobuf_c_boolean has_terminal;
  uint32_t terminal;
  protobuf_c_boolean has_errnum;
  uint32_t errnum;
  char *errmsg;
};
#define CHAT_ONLINE_ACK_MESG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_online_ack_mesg__descriptor) \
    , 0,0, 0,0, NULL, NULL, 0,0, 0,0, NULL }


/* ChatOnlineAckMesg methods */
void   chat_online_ack_mesg__init
                     (ChatOnlineAckMesg         *message);
size_t chat_online_ack_mesg__get_packed_size
                     (const ChatOnlineAckMesg   *message);
size_t chat_online_ack_mesg__pack
                     (const ChatOnlineAckMesg   *message,
                      uint8_t             *out);
size_t chat_online_ack_mesg__pack_to_buffer
                     (const ChatOnlineAckMesg   *message,
                      ProtobufCBuffer     *buffer);
ChatOnlineAckMesg *
       chat_online_ack_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_online_ack_mesg__free_unpacked
                     (ChatOnlineAckMesg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChatOnlineAckMesg_Closure)
                 (const ChatOnlineAckMesg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat_online_ack_mesg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_chat_5fonline_5fack_5fmesg_2eproto__INCLUDED */
