/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "chat_join_ack_mesg.pb-c.h"
void   chat_join_ack_mesg__init
                     (ChatJoinAckMesg         *message)
{
  static ChatJoinAckMesg init_value = CHAT_JOIN_ACK_MESG__INIT;
  *message = init_value;
}
size_t chat_join_ack_mesg__get_packed_size
                     (const ChatJoinAckMesg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_join_ack_mesg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_join_ack_mesg__pack
                     (const ChatJoinAckMesg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_join_ack_mesg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_join_ack_mesg__pack_to_buffer
                     (const ChatJoinAckMesg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_join_ack_mesg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatJoinAckMesg *
       chat_join_ack_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatJoinAckMesg *)
     protobuf_c_message_unpack (&chat_join_ack_mesg__descriptor,
                                allocator, len, data);
}
void   chat_join_ack_mesg__free_unpacked
                     (ChatJoinAckMesg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_join_ack_mesg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_join_ack_mesg__field_descriptors[5] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, has_uid),
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, has_rid),
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, rid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, has_gid),
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errnum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, has_errnum),
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, errnum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatJoinAckMesg, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_join_ack_mesg__field_indices_by_name[] = {
  4,   /* field[4] = errmsg */
  3,   /* field[3] = errnum */
  2,   /* field[2] = gid */
  1,   /* field[1] = rid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange chat_join_ack_mesg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chat_join_ack_mesg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "chat_join_ack_mesg",
  "ChatJoinAckMesg",
  "ChatJoinAckMesg",
  "",
  sizeof(ChatJoinAckMesg),
  5,
  chat_join_ack_mesg__field_descriptors,
  chat_join_ack_mesg__field_indices_by_name,
  1,  chat_join_ack_mesg__number_ranges,
  (ProtobufCMessageInit) chat_join_ack_mesg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
