/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_chat_5froom_5fmesg_2eproto__INCLUDED
#define PROTOBUF_C_chat_5froom_5fmesg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ChatRoomMesg ChatRoomMesg;


/* --- enums --- */


/* --- messages --- */

struct  _ChatRoomMesg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_rid;
  uint64_t rid;
  protobuf_c_boolean has_gid;
  uint32_t gid;
  protobuf_c_boolean has_mesg_level;
  uint32_t mesg_level;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define CHAT_ROOM_MESG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_room_mesg__descriptor) \
    , 0,0, 0,0, 0,0, 0,{0,NULL} }


/* ChatRoomMesg methods */
void   chat_room_mesg__init
                     (ChatRoomMesg         *message);
size_t chat_room_mesg__get_packed_size
                     (const ChatRoomMesg   *message);
size_t chat_room_mesg__pack
                     (const ChatRoomMesg   *message,
                      uint8_t             *out);
size_t chat_room_mesg__pack_to_buffer
                     (const ChatRoomMesg   *message,
                      ProtobufCBuffer     *buffer);
ChatRoomMesg *
       chat_room_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_room_mesg__free_unpacked
                     (ChatRoomMesg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChatRoomMesg_Closure)
                 (const ChatRoomMesg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat_room_mesg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_chat_5froom_5fmesg_2eproto__INCLUDED */
