/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_chat_5fjoin_5fack_5fmesg_2eproto__INCLUDED
#define PROTOBUF_C_chat_5fjoin_5fack_5fmesg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ChatJoinAckMesg ChatJoinAckMesg;


/* --- enums --- */


/* --- messages --- */

struct  _ChatJoinAckMesg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uid;
  uint64_t uid;
  protobuf_c_boolean has_rid;
  uint64_t rid;
  protobuf_c_boolean has_gid;
  uint32_t gid;
  protobuf_c_boolean has_errnum;
  uint32_t errnum;
  char *errmsg;
};
#define CHAT_JOIN_ACK_MESG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_join_ack_mesg__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, NULL }


/* ChatJoinAckMesg methods */
void   chat_join_ack_mesg__init
                     (ChatJoinAckMesg         *message);
size_t chat_join_ack_mesg__get_packed_size
                     (const ChatJoinAckMesg   *message);
size_t chat_join_ack_mesg__pack
                     (const ChatJoinAckMesg   *message,
                      uint8_t             *out);
size_t chat_join_ack_mesg__pack_to_buffer
                     (const ChatJoinAckMesg   *message,
                      ProtobufCBuffer     *buffer);
ChatJoinAckMesg *
       chat_join_ack_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_join_ack_mesg__free_unpacked
                     (ChatJoinAckMesg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChatJoinAckMesg_Closure)
                 (const ChatJoinAckMesg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat_join_ack_mesg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_chat_5fjoin_5fack_5fmesg_2eproto__INCLUDED */
