/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_chat_5fonline_5fmesg_2eproto__INCLUDED
#define PROTOBUF_C_chat_5fonline_5fmesg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ChatOnlineMesg ChatOnlineMesg;


/* --- enums --- */


/* --- messages --- */

struct  _ChatOnlineMesg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uid;
  uint64_t uid;
  char *token;
  char *app;
  char *version;
  protobuf_c_boolean has_terminal;
  uint32_t terminal;
};
#define CHAT_ONLINE_MESG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_online_mesg__descriptor) \
    , 0,0, NULL, NULL, NULL, 0,0 }


/* ChatOnlineMesg methods */
void   chat_online_mesg__init
                     (ChatOnlineMesg         *message);
size_t chat_online_mesg__get_packed_size
                     (const ChatOnlineMesg   *message);
size_t chat_online_mesg__pack
                     (const ChatOnlineMesg   *message,
                      uint8_t             *out);
size_t chat_online_mesg__pack_to_buffer
                     (const ChatOnlineMesg   *message,
                      ProtobufCBuffer     *buffer);
ChatOnlineMesg *
       chat_online_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_online_mesg__free_unpacked
                     (ChatOnlineMesg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChatOnlineMesg_Closure)
                 (const ChatOnlineMesg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat_online_mesg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_chat_5fonline_5fmesg_2eproto__INCLUDED */
