// Code generated by protoc-gen-go.
// source: join/mesg_join.proto
// DO NOT EDIT!

/*
Package mesg_join is a generated protocol buffer package.

It is generated from these files:
	join/mesg_join.proto

It has these top-level messages:
	MesgJoinReq
*/
package mesg_join

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgJoinReq struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,opt,name=Rid" json:"Rid,omitempty"`
	Token            *string `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgJoinReq) Reset()         { *m = MesgJoinReq{} }
func (m *MesgJoinReq) String() string { return proto.CompactTextString(m) }
func (*MesgJoinReq) ProtoMessage()    {}

func (m *MesgJoinReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgJoinReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgJoinReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}
