/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_mesg_5fonline_5fack_2eproto__INCLUDED
#define PROTOBUF_C_mesg_5fonline_5fack_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _MesgOnlineAck MesgOnlineAck;


/* --- enums --- */


/* --- messages --- */

struct  _MesgOnlineAck
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uid;
  uint64_t uid;
  protobuf_c_boolean has_sid;
  uint64_t sid;
  char *app;
  char *version;
  protobuf_c_boolean has_terminal;
  uint32_t terminal;
  protobuf_c_boolean has_errnum;
  uint32_t errnum;
  char *errmsg;
};
#define MESG_ONLINE_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg_online_ack__descriptor) \
    , 0,0, 0,0, NULL, NULL, 0,0, 0,0, NULL }


/* MesgOnlineAck methods */
void   mesg_online_ack__init
                     (MesgOnlineAck         *message);
size_t mesg_online_ack__get_packed_size
                     (const MesgOnlineAck   *message);
size_t mesg_online_ack__pack
                     (const MesgOnlineAck   *message,
                      uint8_t             *out);
size_t mesg_online_ack__pack_to_buffer
                     (const MesgOnlineAck   *message,
                      ProtobufCBuffer     *buffer);
MesgOnlineAck *
       mesg_online_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg_online_ack__free_unpacked
                     (MesgOnlineAck *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MesgOnlineAck_Closure)
                 (const MesgOnlineAck *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg_online_ack__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_mesg_5fonline_5fack_2eproto__INCLUDED */
