/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg_join.proto */

#ifndef PROTOBUF_C_mesg_5fjoin_2eproto__INCLUDED
#define PROTOBUF_C_mesg_5fjoin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MesgJoinReq MesgJoinReq;


/* --- enums --- */


/* --- messages --- */

struct  _MesgJoinReq
{
  ProtobufCMessage base;
  uint64_t uid;
  uint64_t rid;
  char *token;
};
#define MESG_JOIN_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg_join_req__descriptor) \
    , 0, 0, NULL }


/* MesgJoinReq methods */
void   mesg_join_req__init
                     (MesgJoinReq         *message);
size_t mesg_join_req__get_packed_size
                     (const MesgJoinReq   *message);
size_t mesg_join_req__pack
                     (const MesgJoinReq   *message,
                      uint8_t             *out);
size_t mesg_join_req__pack_to_buffer
                     (const MesgJoinReq   *message,
                      ProtobufCBuffer     *buffer);
MesgJoinReq *
       mesg_join_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg_join_req__free_unpacked
                     (MesgJoinReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MesgJoinReq_Closure)
                 (const MesgJoinReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg_join_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mesg_5fjoin_2eproto__INCLUDED */
