/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg_room.proto */

#ifndef PROTOBUF_C_mesg_5froom_2eproto__INCLUDED
#define PROTOBUF_C_mesg_5froom_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MesgRoom MesgRoom;


/* --- enums --- */


/* --- messages --- */

struct  _MesgRoom
{
  ProtobufCMessage base;
  uint64_t rid;
  uint32_t gid;
  uint32_t level;
  ProtobufCBinaryData data;
};
#define MESG_ROOM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg_room__descriptor) \
    , 0, 0, 0, {0,NULL} }


/* MesgRoom methods */
void   mesg_room__init
                     (MesgRoom         *message);
size_t mesg_room__get_packed_size
                     (const MesgRoom   *message);
size_t mesg_room__pack
                     (const MesgRoom   *message,
                      uint8_t             *out);
size_t mesg_room__pack_to_buffer
                     (const MesgRoom   *message,
                      ProtobufCBuffer     *buffer);
MesgRoom *
       mesg_room__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg_room__free_unpacked
                     (MesgRoom *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MesgRoom_Closure)
                 (const MesgRoom *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg_room__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mesg_5froom_2eproto__INCLUDED */
