/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg_online_ack.proto */

#ifndef PROTOBUF_C_mesg_5fonline_5fack_2eproto__INCLUDED
#define PROTOBUF_C_mesg_5fonline_5fack_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MesgOnlineAck MesgOnlineAck;


/* --- enums --- */


/* --- messages --- */

struct  _MesgOnlineAck
{
  ProtobufCMessage base;
  uint64_t uid;
  uint64_t sid;
  char *app;
  char *version;
  protobuf_c_boolean has_terminal;
  uint32_t terminal;
  protobuf_c_boolean has_code;
  uint32_t code;
  char *errmsg;
};
#define MESG_ONLINE_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg_online_ack__descriptor) \
    , 0, 0, NULL, NULL, 0,0, 0,0, NULL }


/* MesgOnlineAck methods */
void   mesg_online_ack__init
                     (MesgOnlineAck         *message);
size_t mesg_online_ack__get_packed_size
                     (const MesgOnlineAck   *message);
size_t mesg_online_ack__pack
                     (const MesgOnlineAck   *message,
                      uint8_t             *out);
size_t mesg_online_ack__pack_to_buffer
                     (const MesgOnlineAck   *message,
                      ProtobufCBuffer     *buffer);
MesgOnlineAck *
       mesg_online_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg_online_ack__free_unpacked
                     (MesgOnlineAck *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MesgOnlineAck_Closure)
                 (const MesgOnlineAck *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg_online_ack__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mesg_5fonline_5fack_2eproto__INCLUDED */
