/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_mesg_5fonline_2eproto__INCLUDED
#define PROTOBUF_C_mesg_5fonline_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _MesgOnline MesgOnline;


/* --- enums --- */


/* --- messages --- */

struct  _MesgOnline
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uid;
  uint64_t uid;
  char *token;
  char *app;
  char *version;
  protobuf_c_boolean has_terminal;
  uint32_t terminal;
};
#define MESG_ONLINE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg_online__descriptor) \
    , 0,0, NULL, NULL, NULL, 0,0 }


/* MesgOnline methods */
void   mesg_online__init
                     (MesgOnline         *message);
size_t mesg_online__get_packed_size
                     (const MesgOnline   *message);
size_t mesg_online__pack
                     (const MesgOnline   *message,
                      uint8_t             *out);
size_t mesg_online__pack_to_buffer
                     (const MesgOnline   *message,
                      ProtobufCBuffer     *buffer);
MesgOnline *
       mesg_online__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg_online__free_unpacked
                     (MesgOnline *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MesgOnline_Closure)
                 (const MesgOnline *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg_online__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_mesg_5fonline_2eproto__INCLUDED */
