/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "chat_online_ack_mesg.pb-c.h"
void   chat_online_ack_mesg__init
                     (ChatOnlineAckMesg         *message)
{
  static ChatOnlineAckMesg init_value = CHAT_ONLINE_ACK_MESG__INIT;
  *message = init_value;
}
size_t chat_online_ack_mesg__get_packed_size
                     (const ChatOnlineAckMesg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_ack_mesg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_online_ack_mesg__pack
                     (const ChatOnlineAckMesg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_ack_mesg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_online_ack_mesg__pack_to_buffer
                     (const ChatOnlineAckMesg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_ack_mesg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatOnlineAckMesg *
       chat_online_ack_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatOnlineAckMesg *)
     protobuf_c_message_unpack (&chat_online_ack_mesg__descriptor,
                                allocator, len, data);
}
void   chat_online_ack_mesg__free_unpacked
                     (ChatOnlineAckMesg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_ack_mesg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_online_ack_mesg__field_descriptors[7] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, has_uid),
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, has_cid),
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, app),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terminal",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, has_terminal),
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, terminal),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errnum",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, has_errnum),
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, errnum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineAckMesg, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_online_ack_mesg__field_indices_by_name[] = {
  2,   /* field[2] = app */
  1,   /* field[1] = cid */
  6,   /* field[6] = errmsg */
  5,   /* field[5] = errnum */
  4,   /* field[4] = terminal */
  0,   /* field[0] = uid */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange chat_online_ack_mesg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor chat_online_ack_mesg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "chat_online_ack_mesg",
  "ChatOnlineAckMesg",
  "ChatOnlineAckMesg",
  "",
  sizeof(ChatOnlineAckMesg),
  7,
  chat_online_ack_mesg__field_descriptors,
  chat_online_ack_mesg__field_indices_by_name,
  1,  chat_online_ack_mesg__number_ranges,
  (ProtobufCMessageInit) chat_online_ack_mesg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
