/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "chat_online_mesg.pb-c.h"
void   chat_online_mesg__init
                     (ChatOnlineMesg         *message)
{
  static ChatOnlineMesg init_value = CHAT_ONLINE_MESG__INIT;
  *message = init_value;
}
size_t chat_online_mesg__get_packed_size
                     (const ChatOnlineMesg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_mesg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_online_mesg__pack
                     (const ChatOnlineMesg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_mesg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_online_mesg__pack_to_buffer
                     (const ChatOnlineMesg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_mesg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatOnlineMesg *
       chat_online_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatOnlineMesg *)
     protobuf_c_message_unpack (&chat_online_mesg__descriptor,
                                allocator, len, data);
}
void   chat_online_mesg__free_unpacked
                     (ChatOnlineMesg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_online_mesg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_online_mesg__field_descriptors[5] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, has_uid),
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, token),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, app),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terminal",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, has_terminal),
    PROTOBUF_C_OFFSETOF(ChatOnlineMesg, terminal),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_online_mesg__field_indices_by_name[] = {
  2,   /* field[2] = app */
  4,   /* field[4] = terminal */
  1,   /* field[1] = token */
  0,   /* field[0] = uid */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange chat_online_mesg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chat_online_mesg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "chat_online_mesg",
  "ChatOnlineMesg",
  "ChatOnlineMesg",
  "",
  sizeof(ChatOnlineMesg),
  5,
  chat_online_mesg__field_descriptors,
  chat_online_mesg__field_indices_by_name,
  1,  chat_online_mesg__number_ranges,
  (ProtobufCMessageInit) chat_online_mesg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
