/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "chat_room_mesg.pb-c.h"
void   chat_room_mesg__init
                     (ChatRoomMesg         *message)
{
  static ChatRoomMesg init_value = CHAT_ROOM_MESG__INIT;
  *message = init_value;
}
size_t chat_room_mesg__get_packed_size
                     (const ChatRoomMesg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_room_mesg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_room_mesg__pack
                     (const ChatRoomMesg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_room_mesg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_room_mesg__pack_to_buffer
                     (const ChatRoomMesg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_room_mesg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatRoomMesg *
       chat_room_mesg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatRoomMesg *)
     protobuf_c_message_unpack (&chat_room_mesg__descriptor,
                                allocator, len, data);
}
void   chat_room_mesg__free_unpacked
                     (ChatRoomMesg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chat_room_mesg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_room_mesg__field_descriptors[4] =
{
  {
    "rid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, has_rid),
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, rid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, has_gid),
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mesg_level",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, has_mesg_level),
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, mesg_level),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, has_data),
    PROTOBUF_C_OFFSETOF(ChatRoomMesg, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_room_mesg__field_indices_by_name[] = {
  3,   /* field[3] = data */
  1,   /* field[1] = gid */
  2,   /* field[2] = mesg_level */
  0,   /* field[0] = rid */
};
static const ProtobufCIntRange chat_room_mesg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor chat_room_mesg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "chat_room_mesg",
  "ChatRoomMesg",
  "ChatRoomMesg",
  "",
  sizeof(ChatRoomMesg),
  4,
  chat_room_mesg__field_descriptors,
  chat_room_mesg__field_indices_by_name,
  1,  chat_room_mesg__number_ranges,
  (ProtobufCMessageInit) chat_room_mesg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
