/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "mesg_room.pb-c.h"
void   mesg_room__init
                     (MesgRoom         *message)
{
  static MesgRoom init_value = MESG_ROOM__INIT;
  *message = init_value;
}
size_t mesg_room__get_packed_size
                     (const MesgRoom *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_room__pack
                     (const MesgRoom *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_room__pack_to_buffer
                     (const MesgRoom *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgRoom *
       mesg_room__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgRoom *)
     protobuf_c_message_unpack (&mesg_room__descriptor,
                                allocator, len, data);
}
void   mesg_room__free_unpacked
                     (MesgRoom *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_room__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesg_room__field_descriptors[4] =
{
  {
    "rid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgRoom, rid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgRoom, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgRoom, level),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgRoom, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_room__field_indices_by_name[] = {
  3,   /* field[3] = data */
  1,   /* field[1] = gid */
  2,   /* field[2] = level */
  0,   /* field[0] = rid */
};
static const ProtobufCIntRange mesg_room__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mesg_room__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_room",
  "MesgRoom",
  "MesgRoom",
  "",
  sizeof(MesgRoom),
  4,
  mesg_room__field_descriptors,
  mesg_room__field_indices_by_name,
  1,  mesg_room__number_ranges,
  (ProtobufCMessageInit) mesg_room__init,
  NULL,NULL,NULL    /* reserved[123] */
};
