/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "mesg_join_ack.pb-c.h"
void   mesg_join_ack__init
                     (MesgJoinAck         *message)
{
  static MesgJoinAck init_value = MESG_JOIN_ACK__INIT;
  *message = init_value;
}
size_t mesg_join_ack__get_packed_size
                     (const MesgJoinAck *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_join_ack__pack
                     (const MesgJoinAck *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_join_ack__pack_to_buffer
                     (const MesgJoinAck *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgJoinAck *
       mesg_join_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgJoinAck *)
     protobuf_c_message_unpack (&mesg_join_ack__descriptor,
                                allocator, len, data);
}
void   mesg_join_ack__free_unpacked
                     (MesgJoinAck *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mesg_join_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesg_join_ack__field_descriptors[5] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgJoinAck, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgJoinAck, rid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgJoinAck, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errnum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(MesgJoinAck, has_errnum),
    PROTOBUF_C_OFFSETOF(MesgJoinAck, errnum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MesgJoinAck, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_join_ack__field_indices_by_name[] = {
  4,   /* field[4] = errmsg */
  3,   /* field[3] = errnum */
  2,   /* field[2] = gid */
  1,   /* field[1] = rid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange mesg_join_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mesg_join_ack__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_join_ack",
  "MesgJoinAck",
  "MesgJoinAck",
  "",
  sizeof(MesgJoinAck),
  5,
  mesg_join_ack__field_descriptors,
  mesg_join_ack__field_indices_by_name,
  1,  mesg_join_ack__number_ranges,
  (ProtobufCMessageInit) mesg_join_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
