/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mesg.pb-c.h"
void   mesg_online_req__init
                     (MesgOnlineReq         *message)
{
  static MesgOnlineReq init_value = MESG_ONLINE_REQ__INIT;
  *message = init_value;
}
size_t mesg_online_req__get_packed_size
                     (const MesgOnlineReq *message)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_online_req__pack
                     (const MesgOnlineReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_online_req__pack_to_buffer
                     (const MesgOnlineReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgOnlineReq *
       mesg_online_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgOnlineReq *)
     protobuf_c_message_unpack (&mesg_online_req__descriptor,
                                allocator, len, data);
}
void   mesg_online_req__free_unpacked
                     (MesgOnlineReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_online_ack__init
                     (MesgOnlineAck         *message)
{
  static MesgOnlineAck init_value = MESG_ONLINE_ACK__INIT;
  *message = init_value;
}
size_t mesg_online_ack__get_packed_size
                     (const MesgOnlineAck *message)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_online_ack__pack
                     (const MesgOnlineAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_online_ack__pack_to_buffer
                     (const MesgOnlineAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgOnlineAck *
       mesg_online_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgOnlineAck *)
     protobuf_c_message_unpack (&mesg_online_ack__descriptor,
                                allocator, len, data);
}
void   mesg_online_ack__free_unpacked
                     (MesgOnlineAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_join_req__init
                     (MesgJoinReq         *message)
{
  static MesgJoinReq init_value = MESG_JOIN_REQ__INIT;
  *message = init_value;
}
size_t mesg_join_req__get_packed_size
                     (const MesgJoinReq *message)
{
  assert(message->base.descriptor == &mesg_join_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_join_req__pack
                     (const MesgJoinReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_join_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_join_req__pack_to_buffer
                     (const MesgJoinReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_join_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgJoinReq *
       mesg_join_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgJoinReq *)
     protobuf_c_message_unpack (&mesg_join_req__descriptor,
                                allocator, len, data);
}
void   mesg_join_req__free_unpacked
                     (MesgJoinReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_join_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_join_ack__init
                     (MesgJoinAck         *message)
{
  static MesgJoinAck init_value = MESG_JOIN_ACK__INIT;
  *message = init_value;
}
size_t mesg_join_ack__get_packed_size
                     (const MesgJoinAck *message)
{
  assert(message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_join_ack__pack
                     (const MesgJoinAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_join_ack__pack_to_buffer
                     (const MesgJoinAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_join_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgJoinAck *
       mesg_join_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgJoinAck *)
     protobuf_c_message_unpack (&mesg_join_ack__descriptor,
                                allocator, len, data);
}
void   mesg_join_ack__free_unpacked
                     (MesgJoinAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_join_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_unjoin_req__init
                     (MesgUnjoinReq         *message)
{
  static MesgUnjoinReq init_value = MESG_UNJOIN_REQ__INIT;
  *message = init_value;
}
size_t mesg_unjoin_req__get_packed_size
                     (const MesgUnjoinReq *message)
{
  assert(message->base.descriptor == &mesg_unjoin_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_unjoin_req__pack
                     (const MesgUnjoinReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_unjoin_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_unjoin_req__pack_to_buffer
                     (const MesgUnjoinReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_unjoin_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgUnjoinReq *
       mesg_unjoin_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgUnjoinReq *)
     protobuf_c_message_unpack (&mesg_unjoin_req__descriptor,
                                allocator, len, data);
}
void   mesg_unjoin_req__free_unpacked
                     (MesgUnjoinReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_unjoin_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_room__init
                     (MesgRoom         *message)
{
  static MesgRoom init_value = MESG_ROOM__INIT;
  *message = init_value;
}
size_t mesg_room__get_packed_size
                     (const MesgRoom *message)
{
  assert(message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_room__pack
                     (const MesgRoom *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_room__pack_to_buffer
                     (const MesgRoom *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_room__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgRoom *
       mesg_room__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgRoom *)
     protobuf_c_message_unpack (&mesg_room__descriptor,
                                allocator, len, data);
}
void   mesg_room__free_unpacked
                     (MesgRoom *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_room__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_lsn_rpt__init
                     (MesgLsnRpt         *message)
{
  static MesgLsnRpt init_value = MESG_LSN_RPT__INIT;
  *message = init_value;
}
size_t mesg_lsn_rpt__get_packed_size
                     (const MesgLsnRpt *message)
{
  assert(message->base.descriptor == &mesg_lsn_rpt__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_lsn_rpt__pack
                     (const MesgLsnRpt *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_lsn_rpt__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_lsn_rpt__pack_to_buffer
                     (const MesgLsnRpt *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_lsn_rpt__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgLsnRpt *
       mesg_lsn_rpt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgLsnRpt *)
     protobuf_c_message_unpack (&mesg_lsn_rpt__descriptor,
                                allocator, len, data);
}
void   mesg_lsn_rpt__free_unpacked
                     (MesgLsnRpt *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_lsn_rpt__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesg_online_req__field_descriptors[6] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terminal",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MesgOnlineReq, has_terminal),
    offsetof(MesgOnlineReq, terminal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_online_req__field_indices_by_name[] = {
  3,   /* field[3] = app */
  1,   /* field[1] = sid */
  5,   /* field[5] = terminal */
  2,   /* field[2] = token */
  0,   /* field[0] = uid */
  4,   /* field[4] = version */
};
static const ProtobufCIntRange mesg_online_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor mesg_online_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_online_req",
  "MesgOnlineReq",
  "MesgOnlineReq",
  "",
  sizeof(MesgOnlineReq),
  6,
  mesg_online_req__field_descriptors,
  mesg_online_req__field_indices_by_name,
  1,  mesg_online_req__number_ranges,
  (ProtobufCMessageInit) mesg_online_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_online_ack__field_descriptors[7] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terminal",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MesgOnlineAck, has_terminal),
    offsetof(MesgOnlineAck, terminal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_online_ack__field_indices_by_name[] = {
  2,   /* field[2] = app */
  5,   /* field[5] = code */
  6,   /* field[6] = errmsg */
  1,   /* field[1] = sid */
  4,   /* field[4] = terminal */
  0,   /* field[0] = uid */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange mesg_online_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor mesg_online_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_online_ack",
  "MesgOnlineAck",
  "MesgOnlineAck",
  "",
  sizeof(MesgOnlineAck),
  7,
  mesg_online_ack__field_descriptors,
  mesg_online_ack__field_indices_by_name,
  1,  mesg_online_ack__number_ranges,
  (ProtobufCMessageInit) mesg_online_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_join_req__field_descriptors[3] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgJoinReq, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgJoinReq, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgJoinReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_join_req__field_indices_by_name[] = {
  1,   /* field[1] = rid */
  2,   /* field[2] = token */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange mesg_join_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mesg_join_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_join_req",
  "MesgJoinReq",
  "MesgJoinReq",
  "",
  sizeof(MesgJoinReq),
  3,
  mesg_join_req__field_descriptors,
  mesg_join_req__field_indices_by_name,
  1,  mesg_join_req__number_ranges,
  (ProtobufCMessageInit) mesg_join_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_join_ack__field_descriptors[5] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgJoinAck, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgJoinAck, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgJoinAck, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgJoinAck, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgJoinAck, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_join_ack__field_indices_by_name[] = {
  3,   /* field[3] = code */
  4,   /* field[4] = errmsg */
  2,   /* field[2] = gid */
  1,   /* field[1] = rid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange mesg_join_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mesg_join_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_join_ack",
  "MesgJoinAck",
  "MesgJoinAck",
  "",
  sizeof(MesgJoinAck),
  5,
  mesg_join_ack__field_descriptors,
  mesg_join_ack__field_indices_by_name,
  1,  mesg_join_ack__number_ranges,
  (ProtobufCMessageInit) mesg_join_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_unjoin_req__field_descriptors[2] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgUnjoinReq, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgUnjoinReq, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_unjoin_req__field_indices_by_name[] = {
  1,   /* field[1] = rid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange mesg_unjoin_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mesg_unjoin_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_unjoin_req",
  "MesgUnjoinReq",
  "MesgUnjoinReq",
  "",
  sizeof(MesgUnjoinReq),
  2,
  mesg_unjoin_req__field_descriptors,
  mesg_unjoin_req__field_indices_by_name,
  1,  mesg_unjoin_req__number_ranges,
  (ProtobufCMessageInit) mesg_unjoin_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_room__field_descriptors[4] =
{
  {
    "rid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgRoom, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgRoom, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgRoom, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MesgRoom, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_room__field_indices_by_name[] = {
  3,   /* field[3] = data */
  1,   /* field[1] = gid */
  2,   /* field[2] = level */
  0,   /* field[0] = rid */
};
static const ProtobufCIntRange mesg_room__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mesg_room__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_room",
  "MesgRoom",
  "MesgRoom",
  "",
  sizeof(MesgRoom),
  4,
  mesg_room__field_descriptors,
  mesg_room__field_indices_by_name,
  1,  mesg_room__number_ranges,
  (ProtobufCMessageInit) mesg_room__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_lsn_rpt__field_descriptors[5] =
{
  {
    "nid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsnRpt, nid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgLsnRpt, nation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgLsnRpt, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipaddr",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgLsnRpt, ipaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsnRpt, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_lsn_rpt__field_indices_by_name[] = {
  3,   /* field[3] = ipaddr */
  2,   /* field[2] = name */
  1,   /* field[1] = nation */
  0,   /* field[0] = nid */
  4,   /* field[4] = port */
};
static const ProtobufCIntRange mesg_lsn_rpt__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mesg_lsn_rpt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_lsn_rpt",
  "MesgLsnRpt",
  "MesgLsnRpt",
  "",
  sizeof(MesgLsnRpt),
  5,
  mesg_lsn_rpt__field_descriptors,
  mesg_lsn_rpt__field_indices_by_name,
  1,  mesg_lsn_rpt__number_ranges,
  (ProtobufCMessageInit) mesg_lsn_rpt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
