/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg_online.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mesg_online.pb-c.h"
void   mesg_online_req__init
                     (MesgOnlineReq         *message)
{
  static MesgOnlineReq init_value = MESG_ONLINE_REQ__INIT;
  *message = init_value;
}
size_t mesg_online_req__get_packed_size
                     (const MesgOnlineReq *message)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_online_req__pack
                     (const MesgOnlineReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_online_req__pack_to_buffer
                     (const MesgOnlineReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgOnlineReq *
       mesg_online_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgOnlineReq *)
     protobuf_c_message_unpack (&mesg_online_req__descriptor,
                                allocator, len, data);
}
void   mesg_online_req__free_unpacked
                     (MesgOnlineReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_online_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesg_online_req__field_descriptors[6] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineReq, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terminal",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MesgOnlineReq, has_terminal),
    offsetof(MesgOnlineReq, terminal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_online_req__field_indices_by_name[] = {
  3,   /* field[3] = app */
  1,   /* field[1] = sid */
  5,   /* field[5] = terminal */
  2,   /* field[2] = token */
  0,   /* field[0] = uid */
  4,   /* field[4] = version */
};
static const ProtobufCIntRange mesg_online_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor mesg_online_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_online_req",
  "MesgOnlineReq",
  "MesgOnlineReq",
  "",
  sizeof(MesgOnlineReq),
  6,
  mesg_online_req__field_descriptors,
  mesg_online_req__field_indices_by_name,
  1,  mesg_online_req__number_ranges,
  (ProtobufCMessageInit) mesg_online_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
