// Code generated by protoc-gen-go.
// source: room/mesg_room.proto
// DO NOT EDIT!

/*
Package mesg_room is a generated protocol buffer package.

It is generated from these files:
	room/mesg_room.proto

It has these top-level messages:
	MesgRoom
*/
package mesg_room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgRoom struct {
	Rid              *uint64 `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	Gid              *uint32 `protobuf:"varint,2,opt,name=Gid" json:"Gid,omitempty"`
	MesgLevel        *uint32 `protobuf:"varint,3,opt,name=Mesg_level" json:"Mesg_level,omitempty"`
	Data             []byte  `protobuf:"bytes,4,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoom) Reset()         { *m = MesgRoom{} }
func (m *MesgRoom) String() string { return proto.CompactTextString(m) }
func (*MesgRoom) ProtoMessage()    {}

func (m *MesgRoom) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoom) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgRoom) GetMesgLevel() uint32 {
	if m != nil && m.MesgLevel != nil {
		return *m.MesgLevel
	}
	return 0
}

func (m *MesgRoom) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}
