// Code generated by protoc-gen-go.
// source: mesg_join_ack.proto
// DO NOT EDIT!

/*
Package mesg_join_ack is a generated protocol buffer package.

It is generated from these files:
	mesg_join_ack.proto

It has these top-level messages:
	MesgJoinAck
*/
package mesg_join_ack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgJoinAck struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,opt,name=rid" json:"rid,omitempty"`
	Gid              *uint32 `protobuf:"varint,3,opt,name=gid" json:"gid,omitempty"`
	Errnum           *uint32 `protobuf:"varint,4,opt,name=errnum" json:"errnum,omitempty"`
	Errmsg           *string `protobuf:"bytes,5,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgJoinAck) Reset()         { *m = MesgJoinAck{} }
func (m *MesgJoinAck) String() string { return proto.CompactTextString(m) }
func (*MesgJoinAck) ProtoMessage()    {}

func (m *MesgJoinAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgJoinAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgJoinAck) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgJoinAck) GetErrnum() uint32 {
	if m != nil && m.Errnum != nil {
		return *m.Errnum
	}
	return 0
}

func (m *MesgJoinAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}
