// Code generated by protoc-gen-go.
// source: mesg.proto
// DO NOT EDIT!

/*
Package mesg is a generated protocol buffer package.

It is generated from these files:
	mesg.proto

It has these top-level messages:
	MesgOnlineReq
	MesgOnlineAck
	MesgSubReq
	MesgSubAck
	MesgUnsubReq
	MesgUnsubAck
	MesgUnusualbReq
	MesgSync
	MesgSyncAck
	MesgAllocSeq
	MesgAllocSeqAck
	MesgKickReq
	MesgChat
	MesgChatAck
	MesgFriendAdd
	MesgFriendDel
	MesgBlAdd
	MesgBlDel
	MesgBanAdd
	MesgBanDel
	MesgMarkAdd
	MesgGroupCreat
	MesgGroupCreatAck
	MesgGroupDismiss
	MesgGroupDismissAck
	MesgGroupApply
	MesgGroupApplyAck
	MesgGroupQuit
	MesgGroupQuitAck
	MesgGroupInvite
	MesgGroupInviteAck
	MesgGroupChat
	MesgGroupChatAck
	MesgGroupKick
	MesgGroupKickAck
	MesgGroupBanAdd
	MesgGroupBanAddAck
	MesgGroupBanDel
	MesgGroupBanDelAck
	MesgGroupBlAdd
	MesgGroupBlAddAck
	MesgGroupBlDel
	MesgGroupBlDelAck
	MesgGroupMgrAdd
	MesgGroupMgrAddAck
	MesgGroupMgrDel
	MesgGroupMgrDelAck
	MesgGroupUsrListReq
	MesgGroupUsrListAck
	MesgGroupJoinNtc
	MesgGroupQuitNtc
	MesgGroupKickNtc
	MesgGroupBanAddNtc
	MesgGroupBanDelNtc
	MesgGroupBlAddNtc
	MesgGroupBlDelNtc
	MesgGroupMgrAddNtc
	MesgGroupMgrDelNtc
	MesgRoomCreat
	MesgRoomCreatAck
	MesgRoomDismiss
	MesgRoomDismissAck
	MesgRoomJoin
	MesgRoomJoinAck
	MesgRoomQuit
	MesgRoomQuitAck
	MesgRoomKick
	MesgRoomKickAck
	MesgRoomChat
	MesgRoomChatAck
	MesgRoomBc
	MesgRoomBcAck
	MesgRoomUsrNum
	MesgRoomJoinNtc
	MesgRoomQuitNtc
	MesgRoomKickNtc
	MesgLsnRpt
	MesgFrwdRpt
*/
package mesg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// 命令ID: 0x0101
// 命令描述: 上线请求(ONLINE)
// 协议格式:
type MesgOnlineReq struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Sid              *uint64 `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	App              *string `protobuf:"bytes,4,req,name=app" json:"app,omitempty"`
	Version          *string `protobuf:"bytes,5,req,name=version" json:"version,omitempty"`
	Terminal         *uint32 `protobuf:"varint,6,opt,name=terminal" json:"terminal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgOnlineReq) Reset()                    { *m = MesgOnlineReq{} }
func (m *MesgOnlineReq) String() string            { return proto.CompactTextString(m) }
func (*MesgOnlineReq) ProtoMessage()               {}
func (*MesgOnlineReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MesgOnlineReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgOnlineReq) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *MesgOnlineReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MesgOnlineReq) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *MesgOnlineReq) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *MesgOnlineReq) GetTerminal() uint32 {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return 0
}

//
// 命令ID: 0x0102
// 命令描述: 上线请求应答(ONLINE-ACK)
// 协议格式:
type MesgOnlineAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Sid              *uint64 `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	App              *string `protobuf:"bytes,3,req,name=app" json:"app,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	Terminal         *uint32 `protobuf:"varint,5,opt,name=terminal" json:"terminal,omitempty"`
	Code             *uint32 `protobuf:"varint,6,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,7,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgOnlineAck) Reset()                    { *m = MesgOnlineAck{} }
func (m *MesgOnlineAck) String() string            { return proto.CompactTextString(m) }
func (*MesgOnlineAck) ProtoMessage()               {}
func (*MesgOnlineAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MesgOnlineAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgOnlineAck) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *MesgOnlineAck) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *MesgOnlineAck) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *MesgOnlineAck) GetTerminal() uint32 {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return 0
}

func (m *MesgOnlineAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgOnlineAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0107
// 命令描述: 订阅请求(SUB)
// 协议格式:
type MesgSubReq struct {
	Sub              *uint32 `protobuf:"varint,1,opt,name=sub" json:"sub,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgSubReq) Reset()                    { *m = MesgSubReq{} }
func (m *MesgSubReq) String() string            { return proto.CompactTextString(m) }
func (*MesgSubReq) ProtoMessage()               {}
func (*MesgSubReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MesgSubReq) GetSub() uint32 {
	if m != nil && m.Sub != nil {
		return *m.Sub
	}
	return 0
}

//
// 命令ID: 0x0108
// 命令描述: 订阅应答(SUB-ACK)
// 协议格式:
type MesgSubAck struct {
	Sub              *uint32 `protobuf:"varint,1,req,name=sub" json:"sub,omitempty"`
	Code             *uint32 `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,3,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgSubAck) Reset()                    { *m = MesgSubAck{} }
func (m *MesgSubAck) String() string            { return proto.CompactTextString(m) }
func (*MesgSubAck) ProtoMessage()               {}
func (*MesgSubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MesgSubAck) GetSub() uint32 {
	if m != nil && m.Sub != nil {
		return *m.Sub
	}
	return 0
}

func (m *MesgSubAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgSubAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0109
// 命令描述: 取消订阅(UNSUB)
// 协议格式:
type MesgUnsubReq struct {
	Sub              *uint32 `protobuf:"varint,1,req,name=sub" json:"sub,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgUnsubReq) Reset()                    { *m = MesgUnsubReq{} }
func (m *MesgUnsubReq) String() string            { return proto.CompactTextString(m) }
func (*MesgUnsubReq) ProtoMessage()               {}
func (*MesgUnsubReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MesgUnsubReq) GetSub() uint32 {
	if m != nil && m.Sub != nil {
		return *m.Sub
	}
	return 0
}

//
// 命令ID: 0x010A
// 命令描述: 取消订阅应答(UNSUB-ACK)
// 协议格式:
type MesgUnsubAck struct {
	Sub              *uint32 `protobuf:"varint,1,req,name=sub" json:"sub,omitempty"`
	Code             *uint32 `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,3,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgUnsubAck) Reset()                    { *m = MesgUnsubAck{} }
func (m *MesgUnsubAck) String() string            { return proto.CompactTextString(m) }
func (*MesgUnsubAck) ProtoMessage()               {}
func (*MesgUnsubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MesgUnsubAck) GetSub() uint32 {
	if m != nil && m.Sub != nil {
		return *m.Sub
	}
	return 0
}

func (m *MesgUnsubAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgUnsubAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x010B
// 命令描述: 通用异常消息(UNUSUAL)
// 协议格式:
type MesgUnusualbReq struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgUnusualbReq) Reset()                    { *m = MesgUnusualbReq{} }
func (m *MesgUnusualbReq) String() string            { return proto.CompactTextString(m) }
func (*MesgUnusualbReq) ProtoMessage()               {}
func (*MesgUnusualbReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MesgUnusualbReq) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgUnusualbReq) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x010D
// 命令描述: 同步消息(SYNC)
// 协议格式: NONE
type MesgSync struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgSync) Reset()                    { *m = MesgSync{} }
func (m *MesgSync) String() string            { return proto.CompactTextString(m) }
func (*MesgSync) ProtoMessage()               {}
func (*MesgSync) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MesgSync) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//
// 命令ID: 0x010E
// 命令描述: 同步消息应答(SYNC-ACK)
// 协议格式: NONE
type MesgSyncAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Code             *uint32 `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,3,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgSyncAck) Reset()                    { *m = MesgSyncAck{} }
func (m *MesgSyncAck) String() string            { return proto.CompactTextString(m) }
func (*MesgSyncAck) ProtoMessage()               {}
func (*MesgSyncAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MesgSyncAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgSyncAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgSyncAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0110
// 命令描述: 申请序列号(ALLOC-SEQ)
// 协议格式:
type MesgAllocSeq struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgAllocSeq) Reset()                    { *m = MesgAllocSeq{} }
func (m *MesgAllocSeq) String() string            { return proto.CompactTextString(m) }
func (*MesgAllocSeq) ProtoMessage()               {}
func (*MesgAllocSeq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MesgAllocSeq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgAllocSeq) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

//
// 命令ID: 0x0111
// 命令描述: 申请序列号应答(ALLOC-SEQ-ACK)
// 协议格式:
type MesgAllocSeqAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Seq              *uint64 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	Num              *uint32 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	Code             *uint32 `protobuf:"varint,4,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,5,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgAllocSeqAck) Reset()                    { *m = MesgAllocSeqAck{} }
func (m *MesgAllocSeqAck) String() string            { return proto.CompactTextString(m) }
func (*MesgAllocSeqAck) ProtoMessage()               {}
func (*MesgAllocSeqAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MesgAllocSeqAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgAllocSeqAck) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *MesgAllocSeqAck) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *MesgAllocSeqAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgAllocSeqAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0112
// 命令描述: 踢连接下线(KICK)
// 协议格式:
type MesgKickReq struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgKickReq) Reset()                    { *m = MesgKickReq{} }
func (m *MesgKickReq) String() string            { return proto.CompactTextString(m) }
func (*MesgKickReq) ProtoMessage()               {}
func (*MesgKickReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MesgKickReq) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgKickReq) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0201
// 命令描述: 私聊消息(CHAT)
// 协议格式:
type MesgChat struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	Level            *uint32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Time             *uint64 `protobuf:"varint,4,req,name=time" json:"time,omitempty"`
	Text             *string `protobuf:"bytes,5,req,name=text" json:"text,omitempty"`
	Data             []byte  `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgChat) Reset()                    { *m = MesgChat{} }
func (m *MesgChat) String() string            { return proto.CompactTextString(m) }
func (*MesgChat) ProtoMessage()               {}
func (*MesgChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MesgChat) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgChat) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *MesgChat) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MesgChat) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *MesgChat) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MesgChat) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//
// 命令ID: 0x0202
// 命令描述: 私聊消息应答(CHAT-ACK)
// 协议格式:
type MesgChatAck struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	Code             *uint32 `protobuf:"varint,3,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,4,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgChatAck) Reset()                    { *m = MesgChatAck{} }
func (m *MesgChatAck) String() string            { return proto.CompactTextString(m) }
func (*MesgChatAck) ProtoMessage()               {}
func (*MesgChatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MesgChatAck) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgChatAck) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *MesgChatAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgChatAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0203
// 命令描述: 添加好友(FRIEND-ADD)
// 协议格式:
type MesgFriendAdd struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	Mark             *string `protobuf:"bytes,3,req,name=mark" json:"mark,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgFriendAdd) Reset()                    { *m = MesgFriendAdd{} }
func (m *MesgFriendAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgFriendAdd) ProtoMessage()               {}
func (*MesgFriendAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MesgFriendAdd) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgFriendAdd) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *MesgFriendAdd) GetMark() string {
	if m != nil && m.Mark != nil {
		return *m.Mark
	}
	return ""
}

//
// 命令ID: 0x0205
// 命令描述: 删除好友(FRIEND-DEL)
// 协议格式:
type MesgFriendDel struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgFriendDel) Reset()                    { *m = MesgFriendDel{} }
func (m *MesgFriendDel) String() string            { return proto.CompactTextString(m) }
func (*MesgFriendDel) ProtoMessage()               {}
func (*MesgFriendDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MesgFriendDel) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgFriendDel) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

//
// 命令ID: 0x0207
// 命令描述: 加入黑名单(BL-ADD)
// 协议格式:
type MesgBlAdd struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgBlAdd) Reset()                    { *m = MesgBlAdd{} }
func (m *MesgBlAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgBlAdd) ProtoMessage()               {}
func (*MesgBlAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MesgBlAdd) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgBlAdd) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

//
// 命令ID: 0x0209
// 命令描述: 移除黑名单(BL-DEL)
// 协议格式:
type MesgBlDel struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgBlDel) Reset()                    { *m = MesgBlDel{} }
func (m *MesgBlDel) String() string            { return proto.CompactTextString(m) }
func (*MesgBlDel) ProtoMessage()               {}
func (*MesgBlDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *MesgBlDel) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgBlDel) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

//
// 命令ID: 0x020B
// 命令描述: 屏蔽此人(BAN-ADD)
// 协议格式:
type MesgBanAdd struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgBanAdd) Reset()                    { *m = MesgBanAdd{} }
func (m *MesgBanAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgBanAdd) ProtoMessage()               {}
func (*MesgBanAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *MesgBanAdd) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgBanAdd) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

//
// 命令ID: 0x020D
// 命令描述: 取消屏蔽此人(BAN-DEL)
// 协议格式:
type MesgBanDel struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgBanDel) Reset()                    { *m = MesgBanDel{} }
func (m *MesgBanDel) String() string            { return proto.CompactTextString(m) }
func (*MesgBanDel) ProtoMessage()               {}
func (*MesgBanDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MesgBanDel) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgBanDel) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

//
// 命令ID: 0x0210
// 命令描述: 备注此人(MARK-ADD)
// 协议格式:
type MesgMarkAdd struct {
	Orig             *uint64 `protobuf:"varint,1,req,name=orig" json:"orig,omitempty"`
	Dest             *uint64 `protobuf:"varint,2,req,name=dest" json:"dest,omitempty"`
	Mark             *uint64 `protobuf:"varint,3,req,name=mark" json:"mark,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgMarkAdd) Reset()                    { *m = MesgMarkAdd{} }
func (m *MesgMarkAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgMarkAdd) ProtoMessage()               {}
func (*MesgMarkAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MesgMarkAdd) GetOrig() uint64 {
	if m != nil && m.Orig != nil {
		return *m.Orig
	}
	return 0
}

func (m *MesgMarkAdd) GetDest() uint64 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *MesgMarkAdd) GetMark() uint64 {
	if m != nil && m.Mark != nil {
		return *m.Mark
	}
	return 0
}

//
// 命令ID: 0x0301
// 命令描述: 创建群组(GROUP-CREAT)
// 协议格式:
type MesgGroupCreat struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupCreat) Reset()                    { *m = MesgGroupCreat{} }
func (m *MesgGroupCreat) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupCreat) ProtoMessage()               {}
func (*MesgGroupCreat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *MesgGroupCreat) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupCreat) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0302
// 命令描述: 创建群组应答(GROUP-APPLY-ACK)
// 协议格式:
type MesgGroupCreatAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupCreatAck) Reset()                    { *m = MesgGroupCreatAck{} }
func (m *MesgGroupCreatAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupCreatAck) ProtoMessage()               {}
func (*MesgGroupCreatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *MesgGroupCreatAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupCreatAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0303
// 命令描述: 解散群组(GROUP-DISMISS)
// 协议格式:
type MesgGroupDismiss struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupDismiss) Reset()                    { *m = MesgGroupDismiss{} }
func (m *MesgGroupDismiss) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupDismiss) ProtoMessage()               {}
func (*MesgGroupDismiss) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *MesgGroupDismiss) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupDismiss) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0304
// 命令描述: 解散群组应答(GROUP-DISMISS-ACK)
// 协议格式:
type MesgGroupDismissAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupDismissAck) Reset()                    { *m = MesgGroupDismissAck{} }
func (m *MesgGroupDismissAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupDismissAck) ProtoMessage()               {}
func (*MesgGroupDismissAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *MesgGroupDismissAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupDismissAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0305
// 命令描述: 申请入群(GROUP-APPLY)
// 协议格式:
type MesgGroupApply struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupApply) Reset()                    { *m = MesgGroupApply{} }
func (m *MesgGroupApply) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupApply) ProtoMessage()               {}
func (*MesgGroupApply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *MesgGroupApply) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupApply) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0306
// 命令描述: 申请入群应答(GROUP-APPLY-ACK)
// 协议格式:
type MesgGroupApplyAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupApplyAck) Reset()                    { *m = MesgGroupApplyAck{} }
func (m *MesgGroupApplyAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupApplyAck) ProtoMessage()               {}
func (*MesgGroupApplyAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *MesgGroupApplyAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupApplyAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0307
// 命令描述: 退群(GROUP-QUIT)
// 协议格式:
type MesgGroupQuit struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupQuit) Reset()                    { *m = MesgGroupQuit{} }
func (m *MesgGroupQuit) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupQuit) ProtoMessage()               {}
func (*MesgGroupQuit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *MesgGroupQuit) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupQuit) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0308
// 命令描述: 退群应答(GROUP-QUIT-ACK)
// 协议格式:
type MesgGroupQuitAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupQuitAck) Reset()                    { *m = MesgGroupQuitAck{} }
func (m *MesgGroupQuitAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupQuitAck) ProtoMessage()               {}
func (*MesgGroupQuitAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *MesgGroupQuitAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupQuitAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0309
// 命令描述: 邀请入群(GROUP-INVITE)
// 协议格式:
type MesgGroupInvite struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	To               *uint64 `protobuf:"varint,3,req,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupInvite) Reset()                    { *m = MesgGroupInvite{} }
func (m *MesgGroupInvite) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupInvite) ProtoMessage()               {}
func (*MesgGroupInvite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *MesgGroupInvite) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupInvite) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgGroupInvite) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

//
// 命令ID: 0x030A
// 命令描述: 邀请入群应答(GROUP-INVITE-ACK)
// 协议格式:
type MesgGroupInviteAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupInviteAck) Reset()                    { *m = MesgGroupInviteAck{} }
func (m *MesgGroupInviteAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupInviteAck) ProtoMessage()               {}
func (*MesgGroupInviteAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *MesgGroupInviteAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupInviteAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x030B
// 命令描述: 群聊消息(GROUP-CHAT)
// 协议格式:
type MesgGroupChat struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	Level            *uint32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Time             *uint64 `protobuf:"varint,4,req,name=time" json:"time,omitempty"`
	Text             *string `protobuf:"bytes,5,req,name=text" json:"text,omitempty"`
	Data             []byte  `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupChat) Reset()                    { *m = MesgGroupChat{} }
func (m *MesgGroupChat) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupChat) ProtoMessage()               {}
func (*MesgGroupChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *MesgGroupChat) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupChat) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgGroupChat) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MesgGroupChat) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *MesgGroupChat) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MesgGroupChat) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//
// 命令ID: 0x030C
// 命令描述: 群聊消息应答(GROUP-CHAT-ACK)
// 协议格式:
type MesgGroupChatAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupChatAck) Reset()                    { *m = MesgGroupChatAck{} }
func (m *MesgGroupChatAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupChatAck) ProtoMessage()               {}
func (*MesgGroupChatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *MesgGroupChatAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupChatAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x030D
// 命令描述: 群组踢人(GROUP-KICK)
// 协议格式:
type MesgGroupKick struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupKick) Reset()                    { *m = MesgGroupKick{} }
func (m *MesgGroupKick) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupKick) ProtoMessage()               {}
func (*MesgGroupKick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *MesgGroupKick) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupKick) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x030E
// 命令描述: 群组踢人应答(GROUP-KICK-ACK)
// 协议格式:
type MesgGroupKickAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupKickAck) Reset()                    { *m = MesgGroupKickAck{} }
func (m *MesgGroupKickAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupKickAck) ProtoMessage()               {}
func (*MesgGroupKickAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *MesgGroupKickAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupKickAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0310
// 命令描述: 群组禁言(GROUP-BAN-ADD)
// 协议格式:
type MesgGroupBanAdd struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanAdd) Reset()                    { *m = MesgGroupBanAdd{} }
func (m *MesgGroupBanAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanAdd) ProtoMessage()               {}
func (*MesgGroupBanAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *MesgGroupBanAdd) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBanAdd) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0311
// 命令描述: 群组禁言应答(GROUP-BAN-ADD-ACK)
// 协议格式:
type MesgGroupBanAddAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanAddAck) Reset()                    { *m = MesgGroupBanAddAck{} }
func (m *MesgGroupBanAddAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanAddAck) ProtoMessage()               {}
func (*MesgGroupBanAddAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *MesgGroupBanAddAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupBanAddAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0312
// 命令描述: 解除群组禁言(GROUP-BAN-DEL)
// 协议格式:
type MesgGroupBanDel struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanDel) Reset()                    { *m = MesgGroupBanDel{} }
func (m *MesgGroupBanDel) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanDel) ProtoMessage()               {}
func (*MesgGroupBanDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *MesgGroupBanDel) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBanDel) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0313
// 命令描述: 解除群组禁言应答(GROUP-BAN-DEL-ACK)
// 协议格式:
type MesgGroupBanDelAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanDelAck) Reset()                    { *m = MesgGroupBanDelAck{} }
func (m *MesgGroupBanDelAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanDelAck) ProtoMessage()               {}
func (*MesgGroupBanDelAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *MesgGroupBanDelAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupBanDelAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0314
// 命令描述: 加入群组黑名单(GROUP-BL-ADD)
// 协议格式:
type MesgGroupBlAdd struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlAdd) Reset()                    { *m = MesgGroupBlAdd{} }
func (m *MesgGroupBlAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlAdd) ProtoMessage()               {}
func (*MesgGroupBlAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *MesgGroupBlAdd) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBlAdd) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0315
// 命令描述: 加入群组黑名单应答(GROUP-BL-ADD-ACK)
// 协议格式:
type MesgGroupBlAddAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlAddAck) Reset()                    { *m = MesgGroupBlAddAck{} }
func (m *MesgGroupBlAddAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlAddAck) ProtoMessage()               {}
func (*MesgGroupBlAddAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *MesgGroupBlAddAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupBlAddAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0316
// 命令描述: 移除群组黑名单(GROUP-BL-DEL)
// 协议格式:
type MesgGroupBlDel struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlDel) Reset()                    { *m = MesgGroupBlDel{} }
func (m *MesgGroupBlDel) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlDel) ProtoMessage()               {}
func (*MesgGroupBlDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *MesgGroupBlDel) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBlDel) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0317
// 命令描述: 移除群组黑名单应答(GROUP-BL-DEL-ACK)
// 协议格式:
type MesgGroupBlDelAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlDelAck) Reset()                    { *m = MesgGroupBlDelAck{} }
func (m *MesgGroupBlDelAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlDelAck) ProtoMessage()               {}
func (*MesgGroupBlDelAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *MesgGroupBlDelAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupBlDelAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0318
// 命令描述: 添加群组管理员(GROUP-MGR-ADD)
// 协议格式:
type MesgGroupMgrAdd struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrAdd) Reset()                    { *m = MesgGroupMgrAdd{} }
func (m *MesgGroupMgrAdd) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrAdd) ProtoMessage()               {}
func (*MesgGroupMgrAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *MesgGroupMgrAdd) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupMgrAdd) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0319
// 命令描述: 添加群组管理员应答(GROUP-MGR-ADD-ACK)
// 协议格式:
type MesgGroupMgrAddAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrAddAck) Reset()                    { *m = MesgGroupMgrAddAck{} }
func (m *MesgGroupMgrAddAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrAddAck) ProtoMessage()               {}
func (*MesgGroupMgrAddAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *MesgGroupMgrAddAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupMgrAddAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x031A
// 命令描述: 解除群组管理员(GROUP-MGR-DEL)
// 协议格式:
type MesgGroupMgrDel struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrDel) Reset()                    { *m = MesgGroupMgrDel{} }
func (m *MesgGroupMgrDel) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrDel) ProtoMessage()               {}
func (*MesgGroupMgrDel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *MesgGroupMgrDel) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupMgrDel) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x031B
// 命令描述: 解除群组管理员应答(GROUP-MGR-DEL-ACK)
// 协议格式:
type MesgGroupMgrDelAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrDelAck) Reset()                    { *m = MesgGroupMgrDelAck{} }
func (m *MesgGroupMgrDelAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrDelAck) ProtoMessage()               {}
func (*MesgGroupMgrDelAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *MesgGroupMgrDelAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgGroupMgrDelAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x031C
// 命令描述: 群员列表请求(GROUP-USR-LIST-REQ)
// 协议格式:
type MesgGroupUsrListReq struct {
	Gid              *uint64 `protobuf:"varint,1,req,name=gid" json:"gid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupUsrListReq) Reset()                    { *m = MesgGroupUsrListReq{} }
func (m *MesgGroupUsrListReq) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupUsrListReq) ProtoMessage()               {}
func (*MesgGroupUsrListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *MesgGroupUsrListReq) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgGroupUsrListReq) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

//
// 命令ID: 0x031D
// 命令描述: 群员列表应答(GROUP-USR-LIST-ACK)
// 协议格式:
type MesgGroupUsrListAck struct {
	Gid              *uint64 `protobuf:"varint,1,req,name=gid" json:"gid,omitempty"`
	List             *string `protobuf:"bytes,2,req,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupUsrListAck) Reset()                    { *m = MesgGroupUsrListAck{} }
func (m *MesgGroupUsrListAck) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupUsrListAck) ProtoMessage()               {}
func (*MesgGroupUsrListAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *MesgGroupUsrListAck) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgGroupUsrListAck) GetList() string {
	if m != nil && m.List != nil {
		return *m.List
	}
	return ""
}

//
// 命令ID: 0x0350
// 命令描述: 入群通知(GROUP-JOIN-NTC)
// 协议格式:
type MesgGroupJoinNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupJoinNtc) Reset()                    { *m = MesgGroupJoinNtc{} }
func (m *MesgGroupJoinNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupJoinNtc) ProtoMessage()               {}
func (*MesgGroupJoinNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *MesgGroupJoinNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupJoinNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0351
// 命令描述: 退群通知(GROUP-QUIT-NTC)
// 协议格式:
type MesgGroupQuitNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupQuitNtc) Reset()                    { *m = MesgGroupQuitNtc{} }
func (m *MesgGroupQuitNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupQuitNtc) ProtoMessage()               {}
func (*MesgGroupQuitNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *MesgGroupQuitNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupQuitNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0352
// 命令描述: 踢人通知(GROUP-KICK-NTC)
// 协议格式:
type MesgGroupKickNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupKickNtc) Reset()                    { *m = MesgGroupKickNtc{} }
func (m *MesgGroupKickNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupKickNtc) ProtoMessage()               {}
func (*MesgGroupKickNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *MesgGroupKickNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupKickNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0353
// 命令描述: 禁言通知(GROUP-BAN-ADD-NTC)
// 协议格式:
type MesgGroupBanAddNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanAddNtc) Reset()                    { *m = MesgGroupBanAddNtc{} }
func (m *MesgGroupBanAddNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanAddNtc) ProtoMessage()               {}
func (*MesgGroupBanAddNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *MesgGroupBanAddNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBanAddNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0354
// 命令描述: 解除禁言通知(GROUP-BAN-DEL-NTC)
// 协议格式:
type MesgGroupBanDelNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBanDelNtc) Reset()                    { *m = MesgGroupBanDelNtc{} }
func (m *MesgGroupBanDelNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBanDelNtc) ProtoMessage()               {}
func (*MesgGroupBanDelNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *MesgGroupBanDelNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBanDelNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0355
// 命令描述: 加入黑名单通知(GROUP-BL-ADD-NTC)
// 协议格式:
type MesgGroupBlAddNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlAddNtc) Reset()                    { *m = MesgGroupBlAddNtc{} }
func (m *MesgGroupBlAddNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlAddNtc) ProtoMessage()               {}
func (*MesgGroupBlAddNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

func (m *MesgGroupBlAddNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBlAddNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0356
// 命令描述: 移除黑名单通知(GROUP-BL-DEL-NTC)
// 协议格式:
type MesgGroupBlDelNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupBlDelNtc) Reset()                    { *m = MesgGroupBlDelNtc{} }
func (m *MesgGroupBlDelNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupBlDelNtc) ProtoMessage()               {}
func (*MesgGroupBlDelNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

func (m *MesgGroupBlDelNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupBlDelNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0357
// 命令描述: 添加管理员通知(GROUP-MGR-ADD-NTC)
// 协议格式:
type MesgGroupMgrAddNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrAddNtc) Reset()                    { *m = MesgGroupMgrAddNtc{} }
func (m *MesgGroupMgrAddNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrAddNtc) ProtoMessage()               {}
func (*MesgGroupMgrAddNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *MesgGroupMgrAddNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupMgrAddNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0358
// 命令描述: 移除管理员通知(GROUP-MGR-DEL-NTC)
// 协议格式:
type MesgGroupMgrDelNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid              *uint64 `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgGroupMgrDelNtc) Reset()                    { *m = MesgGroupMgrDelNtc{} }
func (m *MesgGroupMgrDelNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgGroupMgrDelNtc) ProtoMessage()               {}
func (*MesgGroupMgrDelNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

func (m *MesgGroupMgrDelNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgGroupMgrDelNtc) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

//
// 命令ID: 0x0401
// 命令描述: 创建聊天室(ROOM-CREAT)
// 协议格式:
type MesgRoomCreat struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Desc             *string `protobuf:"bytes,4,req,name=desc" json:"desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomCreat) Reset()                    { *m = MesgRoomCreat{} }
func (m *MesgRoomCreat) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomCreat) ProtoMessage()               {}
func (*MesgRoomCreat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

func (m *MesgRoomCreat) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomCreat) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomCreat) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MesgRoomCreat) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

//
// 命令ID: 0x0402
// 命令描述: 创建聊天室应答(ROOM-CREAT-ACK)
// 协议格式:
type MesgRoomCreatAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Code             *uint32 `protobuf:"varint,3,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,4,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomCreatAck) Reset()                    { *m = MesgRoomCreatAck{} }
func (m *MesgRoomCreatAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomCreatAck) ProtoMessage()               {}
func (*MesgRoomCreatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

func (m *MesgRoomCreatAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomCreatAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomCreatAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomCreatAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0403
// 命令描述: 解散聊天室(ROOM-DISMISS)
// 协议格式:
type MesgRoomDismiss struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomDismiss) Reset()                    { *m = MesgRoomDismiss{} }
func (m *MesgRoomDismiss) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomDismiss) ProtoMessage()               {}
func (*MesgRoomDismiss) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

func (m *MesgRoomDismiss) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomDismiss) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

//
// 命令ID: 0x0404
// 命令描述: 解散聊天室应答(ROOM-DISMISS-ACK)
// 协议格式:
type MesgRoomDismissAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomDismissAck) Reset()                    { *m = MesgRoomDismissAck{} }
func (m *MesgRoomDismissAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomDismissAck) ProtoMessage()               {}
func (*MesgRoomDismissAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

func (m *MesgRoomDismissAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomDismissAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0405
// 命令描述: 加入聊天室(ROOM-JOIN)
// 注意事项: 登录成功后 再加入聊天室时 无需再进行token认证.
// 协议格式:
type MesgRoomJoin struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomJoin) Reset()                    { *m = MesgRoomJoin{} }
func (m *MesgRoomJoin) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomJoin) ProtoMessage()               {}
func (*MesgRoomJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{62} }

func (m *MesgRoomJoin) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomJoin) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

//
// 命令ID: 0x0406
// 命令描述: 加入聊天室应答(ROOM-JOIN-ACK)
// 协议格式:
type MesgRoomJoinAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Gid              *uint32 `protobuf:"varint,3,req,name=gid" json:"gid,omitempty"`
	Code             *uint32 `protobuf:"varint,4,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,5,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomJoinAck) Reset()                    { *m = MesgRoomJoinAck{} }
func (m *MesgRoomJoinAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomJoinAck) ProtoMessage()               {}
func (*MesgRoomJoinAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{63} }

func (m *MesgRoomJoinAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomJoinAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomJoinAck) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgRoomJoinAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomJoinAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0407
// 命令描述: 退出聊天室(ROOM-QUIT)
// 协议格式:
type MesgRoomQuit struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomQuit) Reset()                    { *m = MesgRoomQuit{} }
func (m *MesgRoomQuit) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomQuit) ProtoMessage()               {}
func (*MesgRoomQuit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{64} }

func (m *MesgRoomQuit) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomQuit) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

//
// 命令ID: 0x0408
// 命令描述: 退出聊天室应答(ROOM-QUIT-ACK)
// 协议格式:
type MesgRoomQuitAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Code             *uint32 `protobuf:"varint,3,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,4,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomQuitAck) Reset()                    { *m = MesgRoomQuitAck{} }
func (m *MesgRoomQuitAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomQuitAck) ProtoMessage()               {}
func (*MesgRoomQuitAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{65} }

func (m *MesgRoomQuitAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomQuitAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomQuitAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomQuitAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0409
// 命令描述: 踢出聊天室(ROOM-KICK)
// 协议格式:
type MesgRoomKick struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomKick) Reset()                    { *m = MesgRoomKick{} }
func (m *MesgRoomKick) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomKick) ProtoMessage()               {}
func (*MesgRoomKick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{66} }

func (m *MesgRoomKick) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomKick) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

//
// 命令ID: 0x040A
// 命令描述: 踢出聊天室应答(ROOM-KICK-ACK)
// 协议格式:
type MesgRoomKickAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Code             *uint32 `protobuf:"varint,3,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,4,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomKickAck) Reset()                    { *m = MesgRoomKickAck{} }
func (m *MesgRoomKickAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomKickAck) ProtoMessage()               {}
func (*MesgRoomKickAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{67} }

func (m *MesgRoomKickAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomKickAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomKickAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomKickAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x040B
// 命令描述: 聊天室消息(ROOM)
// 协议格式:
type MesgRoomChat struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Gid              *uint32 `protobuf:"varint,3,req,name=gid" json:"gid,omitempty"`
	Level            *uint32 `protobuf:"varint,4,req,name=level" json:"level,omitempty"`
	Time             *uint64 `protobuf:"varint,5,req,name=time" json:"time,omitempty"`
	Text             *string `protobuf:"bytes,6,req,name=text" json:"text,omitempty"`
	Data             []byte  `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomChat) Reset()                    { *m = MesgRoomChat{} }
func (m *MesgRoomChat) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomChat) ProtoMessage()               {}
func (*MesgRoomChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{68} }

func (m *MesgRoomChat) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgRoomChat) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomChat) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgRoomChat) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MesgRoomChat) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *MesgRoomChat) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MesgRoomChat) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//
// 命令ID: 0x040C
// 命令描述: 聊天室消息应答(ROOM-CHAT-ACK)
// 协议格式:
type MesgRoomChatAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomChatAck) Reset()                    { *m = MesgRoomChatAck{} }
func (m *MesgRoomChatAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomChatAck) ProtoMessage()               {}
func (*MesgRoomChatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{69} }

func (m *MesgRoomChatAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomChatAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x040D
// 命令描述: 聊天室广播消息(ROOM-BC)
// 协议格式:
type MesgRoomBc struct {
	Rid              *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Level            *uint32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Time             *uint64 `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Expire           *uint32 `protobuf:"varint,4,req,name=expire" json:"expire,omitempty"`
	Data             []byte  `protobuf:"bytes,5,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomBc) Reset()                    { *m = MesgRoomBc{} }
func (m *MesgRoomBc) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomBc) ProtoMessage()               {}
func (*MesgRoomBc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{70} }

func (m *MesgRoomBc) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomBc) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MesgRoomBc) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *MesgRoomBc) GetExpire() uint32 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *MesgRoomBc) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//
// 命令ID: 0x040E
// 命令描述: 聊天室广播消息应答(ROOM-BC-ACK)
// 协议格式:
type MesgRoomBcAck struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomBcAck) Reset()                    { *m = MesgRoomBcAck{} }
func (m *MesgRoomBcAck) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomBcAck) ProtoMessage()               {}
func (*MesgRoomBcAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{71} }

func (m *MesgRoomBcAck) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MesgRoomBcAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

//
// 命令ID: 0x0410
// 命令描述: 聊天室人数(ROOM-USR-NUM)
// 协议格式:
type MesgRoomUsrNum struct {
	Rid              *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomUsrNum) Reset()                    { *m = MesgRoomUsrNum{} }
func (m *MesgRoomUsrNum) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomUsrNum) ProtoMessage()               {}
func (*MesgRoomUsrNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{72} }

func (m *MesgRoomUsrNum) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgRoomUsrNum) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

//
// 命令ID: 0x0450
// 命令描述: 加入聊天室通知(ROOM-JOIN-NTC)
// 协议格式:
type MesgRoomJoinNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomJoinNtc) Reset()                    { *m = MesgRoomJoinNtc{} }
func (m *MesgRoomJoinNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomJoinNtc) ProtoMessage()               {}
func (*MesgRoomJoinNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{73} }

func (m *MesgRoomJoinNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//
// 命令ID: 0x0451
// 命令描述: 退出聊天室通知(ROOM-QUIT-NTC)
// 协议格式:
type MesgRoomQuitNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomQuitNtc) Reset()                    { *m = MesgRoomQuitNtc{} }
func (m *MesgRoomQuitNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomQuitNtc) ProtoMessage()               {}
func (*MesgRoomQuitNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{74} }

func (m *MesgRoomQuitNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//
// 命令ID: 0x0452
// 命令描述: 踢出聊天室通知(ROOM-KICK-NTC)
// 协议格式:
type MesgRoomKickNtc struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgRoomKickNtc) Reset()                    { *m = MesgRoomKickNtc{} }
func (m *MesgRoomKickNtc) String() string            { return proto.CompactTextString(m) }
func (*MesgRoomKickNtc) ProtoMessage()               {}
func (*MesgRoomKickNtc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{75} }

func (m *MesgRoomKickNtc) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//
// 命令ID: 0x0601
// 命令描述: 帧听层上报(LSN-RPT)
// 协议格式:
type MesgLsnRpt struct {
	Nid              *uint32 `protobuf:"varint,1,req,name=nid" json:"nid,omitempty"`
	Nation           *string `protobuf:"bytes,2,req,name=nation" json:"nation,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Ipaddr           *string `protobuf:"bytes,4,req,name=ipaddr" json:"ipaddr,omitempty"`
	Port             *uint32 `protobuf:"varint,5,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgLsnRpt) Reset()                    { *m = MesgLsnRpt{} }
func (m *MesgLsnRpt) String() string            { return proto.CompactTextString(m) }
func (*MesgLsnRpt) ProtoMessage()               {}
func (*MesgLsnRpt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{76} }

func (m *MesgLsnRpt) GetNid() uint32 {
	if m != nil && m.Nid != nil {
		return *m.Nid
	}
	return 0
}

func (m *MesgLsnRpt) GetNation() string {
	if m != nil && m.Nation != nil {
		return *m.Nation
	}
	return ""
}

func (m *MesgLsnRpt) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MesgLsnRpt) GetIpaddr() string {
	if m != nil && m.Ipaddr != nil {
		return *m.Ipaddr
	}
	return ""
}

func (m *MesgLsnRpt) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

//
// 命令ID: 0x0603
// 命令描述: 转发层上报 (FRWD-RPT)
// 协议格式:
type MesgFrwdRpt struct {
	Nid              *uint32 `protobuf:"varint,1,req,name=nid" json:"nid,omitempty"`
	Ipaddr           *string `protobuf:"bytes,2,req,name=ipaddr" json:"ipaddr,omitempty"`
	ForwardPort      *uint32 `protobuf:"varint,3,req,name=forward_port" json:"forward_port,omitempty"`
	BackendPort      *uint32 `protobuf:"varint,4,req,name=backend_port" json:"backend_port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgFrwdRpt) Reset()                    { *m = MesgFrwdRpt{} }
func (m *MesgFrwdRpt) String() string            { return proto.CompactTextString(m) }
func (*MesgFrwdRpt) ProtoMessage()               {}
func (*MesgFrwdRpt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{77} }

func (m *MesgFrwdRpt) GetNid() uint32 {
	if m != nil && m.Nid != nil {
		return *m.Nid
	}
	return 0
}

func (m *MesgFrwdRpt) GetIpaddr() string {
	if m != nil && m.Ipaddr != nil {
		return *m.Ipaddr
	}
	return ""
}

func (m *MesgFrwdRpt) GetForwardPort() uint32 {
	if m != nil && m.ForwardPort != nil {
		return *m.ForwardPort
	}
	return 0
}

func (m *MesgFrwdRpt) GetBackendPort() uint32 {
	if m != nil && m.BackendPort != nil {
		return *m.BackendPort
	}
	return 0
}

func init() {
	proto.RegisterType((*MesgOnlineReq)(nil), "mesg_online_req")
	proto.RegisterType((*MesgOnlineAck)(nil), "mesg_online_ack")
	proto.RegisterType((*MesgSubReq)(nil), "mesg_sub_req")
	proto.RegisterType((*MesgSubAck)(nil), "mesg_sub_ack")
	proto.RegisterType((*MesgUnsubReq)(nil), "mesg_unsub_req")
	proto.RegisterType((*MesgUnsubAck)(nil), "mesg_unsub_ack")
	proto.RegisterType((*MesgUnusualbReq)(nil), "mesg_unusualb_req")
	proto.RegisterType((*MesgSync)(nil), "mesg_sync")
	proto.RegisterType((*MesgSyncAck)(nil), "mesg_sync_ack")
	proto.RegisterType((*MesgAllocSeq)(nil), "mesg_alloc_seq")
	proto.RegisterType((*MesgAllocSeqAck)(nil), "mesg_alloc_seq_ack")
	proto.RegisterType((*MesgKickReq)(nil), "mesg_kick_req")
	proto.RegisterType((*MesgChat)(nil), "mesg_chat")
	proto.RegisterType((*MesgChatAck)(nil), "mesg_chat_ack")
	proto.RegisterType((*MesgFriendAdd)(nil), "mesg_friend_add")
	proto.RegisterType((*MesgFriendDel)(nil), "mesg_friend_del")
	proto.RegisterType((*MesgBlAdd)(nil), "mesg_bl_add")
	proto.RegisterType((*MesgBlDel)(nil), "mesg_bl_del")
	proto.RegisterType((*MesgBanAdd)(nil), "mesg_ban_add")
	proto.RegisterType((*MesgBanDel)(nil), "mesg_ban_del")
	proto.RegisterType((*MesgMarkAdd)(nil), "mesg_mark_add")
	proto.RegisterType((*MesgGroupCreat)(nil), "mesg_group_creat")
	proto.RegisterType((*MesgGroupCreatAck)(nil), "mesg_group_creat_ack")
	proto.RegisterType((*MesgGroupDismiss)(nil), "mesg_group_dismiss")
	proto.RegisterType((*MesgGroupDismissAck)(nil), "mesg_group_dismiss_ack")
	proto.RegisterType((*MesgGroupApply)(nil), "mesg_group_apply")
	proto.RegisterType((*MesgGroupApplyAck)(nil), "mesg_group_apply_ack")
	proto.RegisterType((*MesgGroupQuit)(nil), "mesg_group_quit")
	proto.RegisterType((*MesgGroupQuitAck)(nil), "mesg_group_quit_ack")
	proto.RegisterType((*MesgGroupInvite)(nil), "mesg_group_invite")
	proto.RegisterType((*MesgGroupInviteAck)(nil), "mesg_group_invite_ack")
	proto.RegisterType((*MesgGroupChat)(nil), "mesg_group_chat")
	proto.RegisterType((*MesgGroupChatAck)(nil), "mesg_group_chat_ack")
	proto.RegisterType((*MesgGroupKick)(nil), "mesg_group_kick")
	proto.RegisterType((*MesgGroupKickAck)(nil), "mesg_group_kick_ack")
	proto.RegisterType((*MesgGroupBanAdd)(nil), "mesg_group_ban_add")
	proto.RegisterType((*MesgGroupBanAddAck)(nil), "mesg_group_ban_add_ack")
	proto.RegisterType((*MesgGroupBanDel)(nil), "mesg_group_ban_del")
	proto.RegisterType((*MesgGroupBanDelAck)(nil), "mesg_group_ban_del_ack")
	proto.RegisterType((*MesgGroupBlAdd)(nil), "mesg_group_bl_add")
	proto.RegisterType((*MesgGroupBlAddAck)(nil), "mesg_group_bl_add_ack")
	proto.RegisterType((*MesgGroupBlDel)(nil), "mesg_group_bl_del")
	proto.RegisterType((*MesgGroupBlDelAck)(nil), "mesg_group_bl_del_ack")
	proto.RegisterType((*MesgGroupMgrAdd)(nil), "mesg_group_mgr_add")
	proto.RegisterType((*MesgGroupMgrAddAck)(nil), "mesg_group_mgr_add_ack")
	proto.RegisterType((*MesgGroupMgrDel)(nil), "mesg_group_mgr_del")
	proto.RegisterType((*MesgGroupMgrDelAck)(nil), "mesg_group_mgr_del_ack")
	proto.RegisterType((*MesgGroupUsrListReq)(nil), "mesg_group_usr_list_req")
	proto.RegisterType((*MesgGroupUsrListAck)(nil), "mesg_group_usr_list_ack")
	proto.RegisterType((*MesgGroupJoinNtc)(nil), "mesg_group_join_ntc")
	proto.RegisterType((*MesgGroupQuitNtc)(nil), "mesg_group_quit_ntc")
	proto.RegisterType((*MesgGroupKickNtc)(nil), "mesg_group_kick_ntc")
	proto.RegisterType((*MesgGroupBanAddNtc)(nil), "mesg_group_ban_add_ntc")
	proto.RegisterType((*MesgGroupBanDelNtc)(nil), "mesg_group_ban_del_ntc")
	proto.RegisterType((*MesgGroupBlAddNtc)(nil), "mesg_group_bl_add_ntc")
	proto.RegisterType((*MesgGroupBlDelNtc)(nil), "mesg_group_bl_del_ntc")
	proto.RegisterType((*MesgGroupMgrAddNtc)(nil), "mesg_group_mgr_add_ntc")
	proto.RegisterType((*MesgGroupMgrDelNtc)(nil), "mesg_group_mgr_del_ntc")
	proto.RegisterType((*MesgRoomCreat)(nil), "mesg_room_creat")
	proto.RegisterType((*MesgRoomCreatAck)(nil), "mesg_room_creat_ack")
	proto.RegisterType((*MesgRoomDismiss)(nil), "mesg_room_dismiss")
	proto.RegisterType((*MesgRoomDismissAck)(nil), "mesg_room_dismiss_ack")
	proto.RegisterType((*MesgRoomJoin)(nil), "mesg_room_join")
	proto.RegisterType((*MesgRoomJoinAck)(nil), "mesg_room_join_ack")
	proto.RegisterType((*MesgRoomQuit)(nil), "mesg_room_quit")
	proto.RegisterType((*MesgRoomQuitAck)(nil), "mesg_room_quit_ack")
	proto.RegisterType((*MesgRoomKick)(nil), "mesg_room_kick")
	proto.RegisterType((*MesgRoomKickAck)(nil), "mesg_room_kick_ack")
	proto.RegisterType((*MesgRoomChat)(nil), "mesg_room_chat")
	proto.RegisterType((*MesgRoomChatAck)(nil), "mesg_room_chat_ack")
	proto.RegisterType((*MesgRoomBc)(nil), "mesg_room_bc")
	proto.RegisterType((*MesgRoomBcAck)(nil), "mesg_room_bc_ack")
	proto.RegisterType((*MesgRoomUsrNum)(nil), "mesg_room_usr_num")
	proto.RegisterType((*MesgRoomJoinNtc)(nil), "mesg_room_join_ntc")
	proto.RegisterType((*MesgRoomQuitNtc)(nil), "mesg_room_quit_ntc")
	proto.RegisterType((*MesgRoomKickNtc)(nil), "mesg_room_kick_ntc")
	proto.RegisterType((*MesgLsnRpt)(nil), "mesg_lsn_rpt")
	proto.RegisterType((*MesgFrwdRpt)(nil), "mesg_frwd_rpt")
}

func init() { proto.RegisterFile("mesg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x58, 0xdb, 0x6e, 0xe3, 0x36,
	0x10, 0x85, 0x65, 0x3b, 0x69, 0x18, 0x3b, 0x49, 0xdd, 0xb4, 0x35, 0x50, 0x14, 0x48, 0xf5, 0x94,
	0xa6, 0x4d, 0xd2, 0x5c, 0x5a, 0x20, 0xdd, 0x0f, 0x58, 0x2c, 0xb0, 0xfb, 0xba, 0x97, 0x27, 0xad,
	0x2c, 0x31, 0x5a, 0xc6, 0x12, 0xa5, 0x50, 0x52, 0x2e, 0x7f, 0xbf, 0xe4, 0x68, 0x64, 0x8b, 0x92,
	0xac, 0x8b, 0xdf, 0x42, 0x73, 0xce, 0x9c, 0x99, 0xe1, 0x70, 0x78, 0x14, 0x42, 0x02, 0x1a, 0x7b,
	0x17, 0x91, 0x08, 0x93, 0xd0, 0x7c, 0x20, 0x87, 0x6a, 0x65, 0x85, 0xdc, 0x67, 0x9c, 0x5a, 0x82,
	0x3e, 0xce, 0xf6, 0xc9, 0x30, 0x65, 0xee, 0x7c, 0x70, 0x62, 0x9c, 0x8e, 0xd4, 0x22, 0x96, 0x0b,
	0x03, 0x16, 0x53, 0x32, 0x4e, 0xc2, 0x25, 0xe5, 0xf3, 0xa1, 0x5c, 0xee, 0xa9, 0x3d, 0x3b, 0x8a,
	0xe6, 0x23, 0x58, 0x1c, 0x92, 0xdd, 0x27, 0x2a, 0x62, 0x16, 0xf2, 0xf9, 0x18, 0x7e, 0x38, 0x22,
	0x3f, 0x24, 0x54, 0x04, 0x8c, 0xdb, 0xfe, 0x7c, 0xe7, 0x64, 0x70, 0x3a, 0x35, 0x5f, 0x75, 0x2e,
	0xdb, 0x59, 0x36, 0x70, 0xa1, 0xf3, 0x61, 0xd9, 0xf9, 0xa8, 0xe2, 0x7c, 0xac, 0x9c, 0xcf, 0x26,
	0x64, 0xe4, 0x84, 0x2e, 0x95, 0x54, 0x86, 0x5c, 0x1d, 0x90, 0x1d, 0x2a, 0x44, 0x10, 0x7b, 0xf3,
	0x5d, 0x65, 0x6f, 0xfe, 0x46, 0x26, 0x40, 0x1d, 0xa7, 0x8b, 0x3c, 0x47, 0xf9, 0xa7, 0xe4, 0x55,
	0x71, 0xdd, 0x15, 0x36, 0x31, 0xa8, 0x6c, 0xd3, 0x28, 0xf8, 0x35, 0x4a, 0x7e, 0x21, 0x30, 0xf3,
	0x77, 0x72, 0x00, 0xd0, 0x94, 0x57, 0x3c, 0x4b, 0x73, 0xf3, 0x8d, 0xb6, 0xdd, 0xd3, 0xf7, 0x15,
	0xf9, 0x11, 0xc1, 0x69, 0x9c, 0xda, 0x7e, 0xe6, 0x3e, 0x87, 0x0c, 0x4a, 0x10, 0x03, 0x20, 0x73,
	0xb2, 0x97, 0x65, 0xf2, 0xca, 0x1d, 0xad, 0xb6, 0xe6, 0xff, 0x64, 0xba, 0xda, 0xa9, 0x56, 0xbe,
	0x39, 0x90, 0x33, 0xcc, 0xc2, 0xf6, 0xfd, 0xd0, 0xb1, 0xe2, 0x9a, 0x16, 0xe1, 0x69, 0x90, 0x61,
	0xcd, 0x2f, 0x64, 0xa6, 0xdb, 0xd6, 0x1f, 0x33, 0x7d, 0x5c, 0x1f, 0xb3, 0x02, 0x0f, 0xb5, 0x7a,
	0x8c, 0x4a, 0x61, 0x40, 0x43, 0x99, 0xe7, 0x98, 0xc2, 0x92, 0x39, 0xcb, 0x0e, 0xb5, 0xf8, 0x8a,
	0xb5, 0x70, 0xbe, 0xd9, 0x89, 0x32, 0x0d, 0x05, 0xf3, 0xd6, 0xe9, 0xba, 0x34, 0x4e, 0xd6, 0x5d,
	0xed, 0xd3, 0x27, 0xea, 0xaf, 0x83, 0x48, 0x58, 0x90, 0x05, 0x01, 0xa6, 0x09, 0x7d, 0x49, 0xb0,
	0xa7, 0x15, 0xd0, 0x4e, 0x6c, 0xe8, 0xe7, 0x89, 0xf9, 0x0e, 0x03, 0x52, 0x0c, 0x90, 0x66, 0x13,
	0x4b, 0x1e, 0xec, 0xb0, 0x14, 0x2c, 0xf4, 0xb3, 0x6c, 0x94, 0xec, 0x6a, 0xdc, 0x0b, 0x46, 0xb9,
	0x6b, 0xd9, 0xae, 0xdb, 0xe6, 0x2c, 0xb0, 0xc5, 0x12, 0xcf, 0xe7, 0x5c, 0x07, 0xbb, 0xd4, 0x6f,
	0x02, 0x9b, 0x7f, 0x92, 0x7d, 0x30, 0x5f, 0xf8, 0x6d, 0x3c, 0x45, 0xd3, 0x36, 0xaf, 0x67, 0x78,
	0x89, 0x16, 0x36, 0x6f, 0x75, 0x5b, 0xb4, 0x6d, 0xf3, 0x7b, 0x87, 0x45, 0x56, 0xf9, 0xf6, 0xaa,
	0xcb, 0xc8, 0xfc, 0x9b, 0x1c, 0x01, 0xd4, 0x13, 0x61, 0x1a, 0x59, 0x8e, 0xa0, 0xb2, 0x11, 0xca,
	0x9d, 0xe8, 0xe5, 0x03, 0xc7, 0xbc, 0x25, 0xc7, 0x65, 0xeb, 0xfc, 0x50, 0x1b, 0xba, 0xec, 0x02,
	0xfb, 0x3d, 0x43, 0xb9, 0x2c, 0x0e, 0x58, 0x1c, 0x37, 0xb0, 0xfc, 0x47, 0x7e, 0xa9, 0xda, 0x77,
	0xe0, 0xd1, 0x73, 0x91, 0x93, 0xd1, 0x7f, 0xed, 0x9c, 0x0b, 0x58, 0x77, 0xe0, 0xf8, 0x0b, 0xfb,
	0x28, 0x43, 0x3d, 0xa6, 0xac, 0xa9, 0x5c, 0x37, 0xe4, 0xa7, 0x92, 0x71, 0x07, 0x86, 0x3b, 0x1c,
	0x69, 0x19, 0x88, 0xf1, 0x27, 0x96, 0xd0, 0xcd, 0x1c, 0x33, 0x42, 0x8c, 0x24, 0xc4, 0xc3, 0xfc,
	0x97, 0xfc, 0x5c, 0x81, 0x76, 0x60, 0x74, 0xb5, 0x9c, 0x60, 0x16, 0x6c, 0xe6, 0xdb, 0x7a, 0x12,
	0xe8, 0xc5, 0x28, 0xce, 0x83, 0xce, 0xe5, 0x56, 0x53, 0xad, 0x73, 0xb9, 0x61, 0x04, 0xf6, 0x6d,
	0xce, 0xfc, 0x66, 0x76, 0x6d, 0x4e, 0xb4, 0xdf, 0x8a, 0x47, 0xdd, 0xea, 0x3e, 0x3c, 0xd2, 0xbe,
	0x03, 0xcf, 0xb9, 0xd6, 0x3e, 0x38, 0xbf, 0x36, 0xd3, 0xe8, 0x2d, 0x93, 0x99, 0x6f, 0xc3, 0xd2,
	0x9c, 0x4c, 0x85, 0xa5, 0x5b, 0x2e, 0x7a, 0xcd, 0x02, 0x4f, 0xf4, 0x3a, 0x1b, 0xb4, 0xdf, 0x8a,
	0xa7, 0xcf, 0xd9, 0xa0, 0x7d, 0x07, 0x9e, 0x1b, 0xf2, 0x6b, 0x01, 0x97, 0xc6, 0xc2, 0xf2, 0x59,
	0x9c, 0xe4, 0x92, 0xc8, 0xab, 0x57, 0x0b, 0xb7, 0xf5, 0x20, 0x94, 0x0c, 0x5e, 0x51, 0x9f, 0xa8,
	0x0d, 0xa4, 0xba, 0xd4, 0xee, 0xc2, 0x43, 0xc8, 0xb8, 0xc5, 0x13, 0xa7, 0x21, 0xa7, 0xcb, 0xea,
	0xac, 0xea, 0x03, 0x80, 0xdb, 0xd6, 0x0c, 0xb8, 0xae, 0xbd, 0x39, 0x7d, 0x31, 0xaa, 0xd2, 0xcd,
	0x98, 0xab, 0xba, 0x96, 0xee, 0x09, 0x69, 0x67, 0xb9, 0xae, 0xed, 0xb5, 0xbe, 0x98, 0x76, 0x9e,
	0xb7, 0x38, 0x01, 0x45, 0x18, 0x06, 0x1b, 0xde, 0x67, 0xb1, 0x1a, 0xce, 0xb2, 0x07, 0xb8, 0x1d,
	0x50, 0xfc, 0x22, 0xc8, 0xde, 0x7d, 0x07, 0xe5, 0xd3, 0x07, 0x3c, 0xaf, 0xb5, 0xa3, 0x5a, 0xd9,
	0xa9, 0x39, 0x6b, 0x50, 0x63, 0xf9, 0x04, 0x00, 0x77, 0x9b, 0xde, 0x74, 0x51, 0x99, 0x00, 0x45,
	0xf3, 0x0e, 0x37, 0x26, 0x97, 0xd5, 0x00, 0x53, 0x5d, 0xdc, 0x40, 0x91, 0xcb, 0xea, 0x95, 0x6d,
	0x4b, 0x7e, 0x58, 0xe6, 0x2e, 0xb2, 0x5a, 0x0b, 0xa3, 0xf6, 0xd1, 0x5f, 0x87, 0xf1, 0xbe, 0x18,
	0xc6, 0xea, 0xcd, 0xdf, 0xb6, 0xcc, 0x1a, 0x73, 0xed, 0xfb, 0xb7, 0x81, 0x79, 0xf5, 0xfc, 0x6d,
	0xcb, 0x1c, 0x15, 0x99, 0x6b, 0x45, 0xc1, 0x86, 0x52, 0xae, 0x14, 0xc2, 0x48, 0x53, 0x08, 0x63,
	0x4d, 0x21, 0xec, 0x68, 0x0a, 0x61, 0x17, 0x14, 0xc2, 0x75, 0x31, 0xfe, 0x8e, 0x02, 0xe1, 0x23,
	0xca, 0x64, 0xc0, 0x2c, 0x9c, 0x3c, 0xac, 0x81, 0xae, 0x55, 0x0c, 0x2d, 0x12, 0x10, 0x4b, 0xe0,
	0xe9, 0x25, 0x62, 0x82, 0xae, 0xe3, 0x84, 0x58, 0x54, 0x9c, 0x13, 0xf3, 0x1f, 0xd4, 0x92, 0xe8,
	0xb7, 0xc7, 0x93, 0x08, 0x08, 0x35, 0xa6, 0xe5, 0x08, 0xd7, 0xc3, 0xd1, 0xc6, 0xfa, 0x1f, 0x95,
	0x6e, 0x2d, 0xcf, 0x01, 0xdd, 0xa4, 0x76, 0x22, 0xeb, 0x26, 0xb5, 0x33, 0xd8, 0xfc, 0x84, 0x15,
	0xf2, 0x63, 0x6e, 0x89, 0x08, 0x4e, 0x91, 0xe3, 0x26, 0x24, 0xc1, 0xed, 0x44, 0xfd, 0xcf, 0xc0,
	0xc8, 0x0f, 0xa4, 0x30, 0x40, 0xe4, 0x2e, 0x8b, 0xe4, 0x58, 0x13, 0xf8, 0x1f, 0x05, 0xb9, 0x1b,
	0x85, 0x22, 0x93, 0x77, 0x53, 0xf3, 0x33, 0x7e, 0x75, 0xdc, 0x8b, 0x67, 0xb7, 0xd6, 0x33, 0x62,
	0x33, 0xcf, 0xc7, 0x64, 0x72, 0x1f, 0x8a, 0x67, 0x5b, 0xb8, 0x16, 0xf8, 0xc8, 0x7a, 0x45, 0xfe,
	0xba, 0x90, 0xa5, 0x55, 0x9f, 0x64, 0xf0, 0x2b, 0x1c, 0xc5, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0x87, 0xd7, 0xe2, 0x7d, 0x11, 0x00, 0x00,
}
