// Code generated by protoc-gen-go.
// source: mesg_online.proto
// DO NOT EDIT!

/*
Package mesg is a generated protocol buffer package.

It is generated from these files:
	mesg_online.proto

It has these top-level messages:
	MesgOnlineReq
	MesgOnlineAck
*/
package mesg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgOnlineReq struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=Uid" json:"Uid,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=Token" json:"Token,omitempty"`
	App              *string `protobuf:"bytes,3,req,name=App" json:"App,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=Version" json:"Version,omitempty"`
	Terminal         *uint32 `protobuf:"varint,5,opt,name=Terminal" json:"Terminal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgOnlineReq) Reset()         { *m = MesgOnlineReq{} }
func (m *MesgOnlineReq) String() string { return proto.CompactTextString(m) }
func (*MesgOnlineReq) ProtoMessage()    {}

func (m *MesgOnlineReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgOnlineReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MesgOnlineReq) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *MesgOnlineReq) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *MesgOnlineReq) GetTerminal() uint32 {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return 0
}

type MesgOnlineAck struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=Uid" json:"Uid,omitempty"`
	Sid              *uint64 `protobuf:"varint,2,req,name=Sid" json:"Sid,omitempty"`
	App              *string `protobuf:"bytes,3,req,name=App" json:"App,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=Version" json:"Version,omitempty"`
	Terminal         *uint32 `protobuf:"varint,5,opt,name=Terminal" json:"Terminal,omitempty"`
	ErrNum           *uint32 `protobuf:"varint,6,opt,name=ErrNum" json:"ErrNum,omitempty"`
	ErrMsg           *string `protobuf:"bytes,7,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgOnlineAck) Reset()         { *m = MesgOnlineAck{} }
func (m *MesgOnlineAck) String() string { return proto.CompactTextString(m) }
func (*MesgOnlineAck) ProtoMessage()    {}

func (m *MesgOnlineAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgOnlineAck) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *MesgOnlineAck) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *MesgOnlineAck) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *MesgOnlineAck) GetTerminal() uint32 {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return 0
}

func (m *MesgOnlineAck) GetErrNum() uint32 {
	if m != nil && m.ErrNum != nil {
		return *m.ErrNum
	}
	return 0
}

func (m *MesgOnlineAck) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}
