// Code generated by protoc-gen-go.
// source: mesg_join.proto
// DO NOT EDIT!

/*
Package mesg is a generated protocol buffer package.

It is generated from these files:
	mesg_join.proto

It has these top-level messages:
	MesgJoinReq
	MesgJoinAck
*/
package mesg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgJoinReq struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,opt,name=Rid" json:"Rid,omitempty"`
	Token            *string `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgJoinReq) Reset()         { *m = MesgJoinReq{} }
func (m *MesgJoinReq) String() string { return proto.CompactTextString(m) }
func (*MesgJoinReq) ProtoMessage()    {}

func (m *MesgJoinReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgJoinReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgJoinReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type MesgJoinAck struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,opt,name=Rid" json:"Rid,omitempty"`
	Gid              *uint32 `protobuf:"varint,3,opt,name=Gid" json:"Gid,omitempty"`
	Errnum           *uint32 `protobuf:"varint,4,opt,name=Errnum" json:"Errnum,omitempty"`
	Errmsg           *string `protobuf:"bytes,5,opt,name=Errmsg" json:"Errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgJoinAck) Reset()         { *m = MesgJoinAck{} }
func (m *MesgJoinAck) String() string { return proto.CompactTextString(m) }
func (*MesgJoinAck) ProtoMessage()    {}

func (m *MesgJoinAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgJoinAck) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *MesgJoinAck) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MesgJoinAck) GetErrnum() uint32 {
	if m != nil && m.Errnum != nil {
		return *m.Errnum
	}
	return 0
}

func (m *MesgJoinAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}
