// Code generated by protoc-gen-go.
// source: mesg_online_ack.proto
// DO NOT EDIT!

/*
Package mesg_online_ack is a generated protocol buffer package.

It is generated from these files:
	mesg_online_ack.proto

It has these top-level messages:
	MesgOnlineAck
*/
package mesg_online_ack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgOnlineAck struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Cid              *uint64 `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	App              *string `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Version          *string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	Terminal         *uint32 `protobuf:"varint,5,opt,name=terminal" json:"terminal,omitempty"`
	Errnum           *uint32 `protobuf:"varint,6,opt,name=errnum" json:"errnum,omitempty"`
	Errmsg           *string `protobuf:"bytes,7,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgOnlineAck) Reset()         { *m = MesgOnlineAck{} }
func (m *MesgOnlineAck) String() string { return proto.CompactTextString(m) }
func (*MesgOnlineAck) ProtoMessage()    {}

func (m *MesgOnlineAck) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgOnlineAck) GetCid() uint64 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *MesgOnlineAck) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *MesgOnlineAck) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *MesgOnlineAck) GetTerminal() uint32 {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return 0
}

func (m *MesgOnlineAck) GetErrnum() uint32 {
	if m != nil && m.Errnum != nil {
		return *m.Errnum
	}
	return 0
}

func (m *MesgOnlineAck) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}
