// Code generated by protoc-gen-go.
// source: mesg_unjoin.proto
// DO NOT EDIT!

/*
Package mesg_unjoin is a generated protocol buffer package.

It is generated from these files:
	mesg_unjoin.proto

It has these top-level messages:
	MesgUnjoinReq
*/
package mesg_unjoin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MesgUnjoinReq struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Rid              *uint64 `protobuf:"varint,2,opt,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MesgUnjoinReq) Reset()         { *m = MesgUnjoinReq{} }
func (m *MesgUnjoinReq) String() string { return proto.CompactTextString(m) }
func (*MesgUnjoinReq) ProtoMessage()    {}

func (m *MesgUnjoinReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MesgUnjoinReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}
